version: '3'
services:
  haid_backend:
    image: haid_backend:latest
    container_name: haid_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - mysql_haid:mysql_haid
      - redis:redis_haid
    depends_on:
      - redis
      - mysql_haid
#    command: /sbin/my_init
  redis:
    image: redis:3.0
    command: ['redis-server', '--requirepass T2LvfRjmRAYntqmOUh7DTbviNn']
    restart: always
    expose:
    - 6379
    ports:
    - "6379:6379"

#  memcached:
#    image: memcached:1.6-alpine
#    restart: always
#    ports:
#      - '11211:11211'
#    command: memcached -m 64

  mysql_haid:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: codemao
      MYSQL_DATABASE: haid
    volumes:
      - ~/mysql:/var/lib/mysql
    ports:
      - '3308:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#volumes:
#  mysql: ~
